const express = require('express');
const path = require('path');
const app = express();
const port = 8080;

// Serve static files from the "dist" directory (Eleventy’s output)
app.use(express.static(path.join(__dirname, 'dist')));

// Serve the home page (generated by Eleventy)
app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, 'dist', 'index.html'));
});

// Catch-all for undefined routes
app.get('*', (req, res) => {
  res.redirect('/404');
});

// Start the server
app.listen(port, () => {
  console.log(`Server running on port ${port}`);
});